/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databaseproject;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author smart view
 */
public class BicyclePage extends javax.swing.JFrame {

    /**
     * Creates new form cyclePage
     */
    String search;
    String vehicleNo;
    String bcBrand;
    String bcModel;
    String bcColor;
    String bcCC;
    String bcFuel;
    String bcCostHr;
    ConnectMSSQL cnObj = new ConnectMSSQL();
    Statement statement;
    
    public BicyclePage() {
        initComponents();
        setResizable(false);
        /* searchMenu.add(searchPanel);*/
        /*searchButton.addActionListener(New ActionListener()
        {
            public void actionPerformed(ActionEvent e)
            {
                
            }
        });*/
        cnObj.connectDB();
    }
 ArrayList<String> reservationForm = new ArrayList<String>(); 
    public void setReservation(ArrayList<String> Form){
    reservationForm=Form;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        BicyclePanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        searchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        VehicleNoField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        BicycleBrandField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        BicycleModelField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        BicycleColorField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        BicycleTypeField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        WheelSizeField = new javax.swing.JTextField();
        VehiclABEL = new javax.swing.JLabel();
        BicycleCostHr = new javax.swing.JTextField();
        BookButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        bgCar = new javax.swing.JLabel();
        NavPanel = new javax.swing.JPanel();
        navReservation = new javax.swing.JButton();
        navUserProfile = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        copyrightLabel = new javax.swing.JLabel();
        navHome = new javax.swing.JButton();
        navAboutUs = new javax.swing.JButton();
        navSignUp = new javax.swing.JButton();
        navFeedback = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jPanel2.setLayout(null);
        jPanel2.add(jTextField1);
        jTextField1.setBounds(20, 110, 180, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Search");
        jPanel2.add(jButton1);
        jButton1.setBounds(230, 110, 80, 30);

        jPanel4.setBackground(new java.awt.Color(51, 0, 51));
        jPanel4.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bicycle Booking");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(20, 0, 290, 60);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(0, 0, 320, 70);

        jPanel5.setLayout(null);
        jPanel5.add(jLabel2);
        jLabel2.setBounds(0, 0, 320, 250);

        jPanel2.add(jPanel5);
        jPanel5.setBounds(0, 190, 320, 250);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(50, 30, 320, 440);

        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Brand Name :");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(10, 80, 100, 20);
        jPanel3.add(jTextField2);
        jTextField2.setBounds(120, 80, 160, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Model Name :");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(10, 110, 100, 30);
        jPanel3.add(jTextField3);
        jTextField3.setBounds(120, 120, 160, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Type :");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(10, 160, 50, 17);
        jPanel3.add(jTextField4);
        jTextField4.setBounds(120, 160, 160, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Wheel Size :");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 200, 90, 17);
        jPanel3.add(jTextField5);
        jTextField5.setBounds(120, 200, 160, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Color :");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(10, 240, 60, 17);
        jPanel3.add(jTextField6);
        jTextField6.setBounds(120, 240, 160, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Cost/hr :");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(10, 280, 64, 17);
        jPanel3.add(jTextField7);
        jTextField7.setBounds(120, 280, 160, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Model ID :");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(10, 330, 71, 17);
        jPanel3.add(jTextField8);
        jTextField8.setBounds(120, 320, 160, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("BOOK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(193, 390, 80, 23);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(20, 390, 73, 20);

        jPanel6.setBackground(new java.awt.Color(51, 0, 51));
        jPanel6.setLayout(null);
        jPanel3.add(jPanel6);
        jPanel6.setBounds(0, 0, 300, 70);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(390, 30, 300, 440);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1270, 680));
        setLocation(new java.awt.Point(0, 0));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1270, 680));
        setMaximumSize(new java.awt.Dimension(1270, 680));
        setMinimumSize(new java.awt.Dimension(1270, 680));
        setResizable(false);
        setSize(new java.awt.Dimension(1270, 680));

        BicyclePanel.setBackground(new java.awt.Color(204, 204, 204));
        BicyclePanel.setMaximumSize(new java.awt.Dimension(1150, 680));
        BicyclePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Bicycle Reservation");
        BicyclePanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 660, 50));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });
        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchFieldKeyReleased(evt);
            }
        });
        jPanel7.add(searchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 220, 40));

        searchButton.setBackground(new java.awt.Color(255, 204, 204));
        searchButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        searchButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchButtonKeyReleased(evt);
            }
        });
        jPanel7.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 90, 40));

        jPanel8.setLayout(null);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseproject/images/BicycleInfo.jpg"))); // NOI18N
        jPanel8.add(jLabel10);
        jLabel10.setBounds(0, 0, 400, 320);

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 400, 320));

        jPanel9.setBackground(new java.awt.Color(51, 0, 51));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Bicycle");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 70));

        BicyclePanel.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 400, 520));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Brand Name :");
        jPanel10.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 100, 20));

        VehicleNoField.setEditable(false);
        VehicleNoField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        VehicleNoField.setMaximumSize(new java.awt.Dimension(210, 40));
        VehicleNoField.setMinimumSize(new java.awt.Dimension(210, 40));
        VehicleNoField.setPreferredSize(new java.awt.Dimension(210, 40));
        VehicleNoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VehicleNoFieldActionPerformed(evt);
            }
        });
        jPanel10.add(VehicleNoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 210, 40));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Model Name :");
        jPanel10.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 100, 30));

        BicycleBrandField.setEditable(false);
        BicycleBrandField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BicycleBrandField.setMaximumSize(new java.awt.Dimension(210, 40));
        BicycleBrandField.setMinimumSize(new java.awt.Dimension(210, 40));
        BicycleBrandField.setPreferredSize(new java.awt.Dimension(210, 40));
        BicycleBrandField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BicycleBrandFieldActionPerformed(evt);
            }
        });
        jPanel10.add(BicycleBrandField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 210, 40));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Wheel Size :");
        jPanel10.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 90, 30));

        BicycleModelField.setEditable(false);
        BicycleModelField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BicycleModelField.setMaximumSize(new java.awt.Dimension(210, 40));
        BicycleModelField.setMinimumSize(new java.awt.Dimension(210, 40));
        BicycleModelField.setPreferredSize(new java.awt.Dimension(210, 40));
        BicycleModelField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BicycleModelFieldActionPerformed(evt);
            }
        });
        jPanel10.add(BicycleModelField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 210, 40));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Type :");
        jPanel10.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 50, 20));

        BicycleColorField.setEditable(false);
        BicycleColorField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BicycleColorField.setMaximumSize(new java.awt.Dimension(210, 40));
        BicycleColorField.setMinimumSize(new java.awt.Dimension(210, 40));
        BicycleColorField.setPreferredSize(new java.awt.Dimension(210, 40));
        jPanel10.add(BicycleColorField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 210, 40));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Color :");
        jPanel10.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, 20));

        BicycleTypeField.setEditable(false);
        BicycleTypeField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BicycleTypeField.setMaximumSize(new java.awt.Dimension(210, 40));
        BicycleTypeField.setMinimumSize(new java.awt.Dimension(210, 40));
        BicycleTypeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BicycleTypeFieldActionPerformed(evt);
            }
        });
        jPanel10.add(BicycleTypeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 210, 40));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Cost/hr :");
        jPanel10.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 70, 20));

        WheelSizeField.setEditable(false);
        WheelSizeField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        WheelSizeField.setMaximumSize(new java.awt.Dimension(210, 40));
        WheelSizeField.setMinimumSize(new java.awt.Dimension(210, 40));
        WheelSizeField.setPreferredSize(new java.awt.Dimension(210, 40));
        WheelSizeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WheelSizeFieldActionPerformed(evt);
            }
        });
        jPanel10.add(WheelSizeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 210, 40));

        VehiclABEL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        VehiclABEL.setText("Vehicle No :");
        jPanel10.add(VehiclABEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 100, 20));

        BicycleCostHr.setEditable(false);
        BicycleCostHr.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BicycleCostHr.setMaximumSize(new java.awt.Dimension(210, 40));
        BicycleCostHr.setMinimumSize(new java.awt.Dimension(210, 40));
        BicycleCostHr.setPreferredSize(new java.awt.Dimension(210, 40));
        jPanel10.add(BicycleCostHr, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 210, -1));

        BookButton.setBackground(new java.awt.Color(0, 153, 153));
        BookButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BookButton.setText("Book");
        BookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookButtonActionPerformed(evt);
            }
        });
        jPanel10.add(BookButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 80, 40));

        BackButton.setBackground(new java.awt.Color(153, 0, 153));
        BackButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        jPanel10.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 90, 40));

        jPanel11.setBackground(new java.awt.Color(51, 0, 51));
        jPanel11.setForeground(new java.awt.Color(51, 0, 51));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Details");
        jPanel11.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 70));

        BicyclePanel.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, 400, 520));

        bgCar.setBackground(new java.awt.Color(153, 153, 153));
        bgCar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseproject/images/bg1.jpg"))); // NOI18N
        bgCar.setMaximumSize(new java.awt.Dimension(1150, 680));
        bgCar.setMinimumSize(new java.awt.Dimension(1150, 680));
        BicyclePanel.add(bgCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 680));

        NavPanel.setBackground(new java.awt.Color(51, 51, 51));
        NavPanel.setMaximumSize(new java.awt.Dimension(120, 680));
        NavPanel.setMinimumSize(new java.awt.Dimension(120, 680));
        NavPanel.setPreferredSize(new java.awt.Dimension(120, 680));
        NavPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navReservation.setBackground(new java.awt.Color(51, 51, 51));
        navReservation.setForeground(new java.awt.Color(255, 255, 255));
        navReservation.setText("RESERVATION");
        navReservation.setToolTipText("");
        navReservation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        navReservation.setMargin(new java.awt.Insets(0, 14, 0, 14));
        navReservation.setMaximumSize(new java.awt.Dimension(77, 30));
        navReservation.setMinimumSize(new java.awt.Dimension(77, 30));
        navReservation.setPreferredSize(new java.awt.Dimension(77, 30));
        navReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navReservationActionPerformed(evt);
            }
        });
        NavPanel.add(navReservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 120, 45));

        navUserProfile.setBackground(new java.awt.Color(51, 51, 51));
        navUserProfile.setForeground(new java.awt.Color(255, 255, 255));
        navUserProfile.setText("USER PROFILE");
        navUserProfile.setToolTipText("");
        navUserProfile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        navUserProfile.setMargin(new java.awt.Insets(0, 14, 0, 14));
        navUserProfile.setMaximumSize(new java.awt.Dimension(77, 30));
        navUserProfile.setMinimumSize(new java.awt.Dimension(77, 30));
        navUserProfile.setPreferredSize(new java.awt.Dimension(77, 30));
        navUserProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navUserProfileActionPerformed(evt);
            }
        });
        NavPanel.add(navUserProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 120, 45));

        titleLabel.setBackground(new java.awt.Color(153, 153, 153));
        titleLabel.setFont(new java.awt.Font("Wide Latin", 3, 14)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(204, 0, 0));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titleLabel.setText("RentAll");
        NavPanel.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 10, 110, 64));

        copyrightLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 2, 16)); // NOI18N
        copyrightLabel.setForeground(new java.awt.Color(255, 255, 255));
        copyrightLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        copyrightLabel.setText("<html><body>Copyright<br>&copy;RentAll</body></html>");
        NavPanel.add(copyrightLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 100, 38));

        navHome.setBackground(new java.awt.Color(51, 51, 51));
        navHome.setForeground(new java.awt.Color(255, 255, 255));
        navHome.setText("HOME");
        navHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        navHome.setMargin(new java.awt.Insets(0, 14, 0, 14));
        navHome.setMaximumSize(new java.awt.Dimension(77, 30));
        navHome.setMinimumSize(new java.awt.Dimension(77, 30));
        navHome.setName(""); // NOI18N
        navHome.setPreferredSize(new java.awt.Dimension(77, 30));
        navHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navHomeActionPerformed(evt);
            }
        });
        NavPanel.add(navHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 120, 45));

        navAboutUs.setBackground(new java.awt.Color(51, 51, 51));
        navAboutUs.setForeground(new java.awt.Color(255, 255, 255));
        navAboutUs.setText("ABOUT US");
        navAboutUs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        navAboutUs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        navAboutUs.setMargin(new java.awt.Insets(0, 14, 0, 14));
        navAboutUs.setMaximumSize(new java.awt.Dimension(77, 30));
        navAboutUs.setMinimumSize(new java.awt.Dimension(77, 30));
        navAboutUs.setName(""); // NOI18N
        navAboutUs.setPreferredSize(new java.awt.Dimension(77, 30));
        navAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navAboutUsActionPerformed(evt);
            }
        });
        NavPanel.add(navAboutUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 120, 45));

        navSignUp.setBackground(new java.awt.Color(51, 51, 51));
        navSignUp.setForeground(new java.awt.Color(255, 255, 255));
        navSignUp.setText("SIGN UP");
        navSignUp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        navSignUp.setMargin(new java.awt.Insets(0, 14, 0, 14));
        navSignUp.setMaximumSize(new java.awt.Dimension(77, 30));
        navSignUp.setMinimumSize(new java.awt.Dimension(77, 30));
        navSignUp.setName(""); // NOI18N
        navSignUp.setPreferredSize(new java.awt.Dimension(77, 30));
        navSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navSignUpActionPerformed(evt);
            }
        });
        NavPanel.add(navSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 120, 45));

        navFeedback.setBackground(new java.awt.Color(51, 51, 51));
        navFeedback.setForeground(new java.awt.Color(255, 255, 255));
        navFeedback.setText("FEEDBACK");
        navFeedback.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        navFeedback.setMargin(new java.awt.Insets(0, 14, 0, 14));
        navFeedback.setMaximumSize(new java.awt.Dimension(120, 45));
        navFeedback.setMinimumSize(new java.awt.Dimension(120, 45));
        navFeedback.setName(""); // NOI18N
        navFeedback.setPreferredSize(new java.awt.Dimension(120, 45));
        navFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navFeedbackActionPerformed(evt);
            }
        });
        NavPanel.add(navFeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 120, 45));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(NavPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BicyclePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NavPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BicyclePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new VehiclePage().setVisible(true);  
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new ReservationPage().setVisible(true);  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void searchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyReleased
        // TODO add your handling code here:
        /*String search=searchField.getText().trim();
        if(!search.equals("")){
            System.out.println("search");
        }
        searchMenu.setVisible(true);
        searchMenu.show(searchField,0,searchField.getHeight());*/
    }//GEN-LAST:event_searchFieldKeyReleased

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        search=searchField.getText();

        if(search.equals(""))
        {
            JOptionPane.showMessageDialog(this, "This bicycle is not available.");    
        }
        else
        { 
        try {
            statement = cnObj.connection.createStatement(); 
            ResultSet resultSet= statement.executeQuery("SELECT BICYCLE.VehicleId, BrandName, ModelName, Color, BicycleType, WheelSize, CostPerHour FROM BICYCLE JOIN VEHICLE ON BICYCLE.VehicleId = VEHICLE.VehicleId AND ModelName ='"+search+"'");
            
             if (resultSet.next()) {
                VehicleNoField.setText(resultSet.getString("VehicleId"));
                BicycleBrandField.setText(resultSet.getString("BrandName"));
                BicycleModelField.setText(resultSet.getString("ModelName"));
                BicycleColorField.setText(resultSet.getString("Color"));
                BicycleTypeField.setText(resultSet.getString("BicycleType"));
                WheelSizeField.setText(resultSet.getString("WheelSize"));
                BicycleCostHr.setText(resultSet.getString("CostPerHour"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(CarPage.class.getName()).log(Level.SEVERE, null, ex);
        }   
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void searchButtonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchButtonKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonKeyReleased

    private void WheelSizeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WheelSizeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WheelSizeFieldActionPerformed

    private void BookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookButtonActionPerformed
        // TODO add your handling code here:
        //new ConfirmationPage().setVisible(true);
        this.dispose();
        ConfirmationPage cfp= new ConfirmationPage();
        // ArrayList<String> reservationForm = new ArrayList<String>();
        cfp.setVisible(true);       
        reservationForm.add(VehicleNoField.getText());
        reservationForm.add(BicycleBrandField.getText());
        reservationForm.add(BicycleModelField.getText());
        reservationForm.add(BicycleCostHr.getText()); 
        cfp.setReservation(reservationForm);
    }//GEN-LAST:event_BookButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        new VehiclePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void navReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navReservationActionPerformed
        // TODO add your handling code here:
        new ReservationPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_navReservationActionPerformed

    private void navUserProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navUserProfileActionPerformed
        // TODO add your handling code here:
        new UserProfilePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_navUserProfileActionPerformed

    private void navHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navHomeActionPerformed
        // TODO add your handling code here:
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_navHomeActionPerformed

    private void navAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navAboutUsActionPerformed
        // TODO add your handling code here:
        new AboutUsPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_navAboutUsActionPerformed

    private void navSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navSignUpActionPerformed
        // TODO add your handling code here:
        new SignUpPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_navSignUpActionPerformed

    private void navFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navFeedbackActionPerformed
        // TODO add your handling code here:
        new FeedbackPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_navFeedbackActionPerformed

    private void VehicleNoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VehicleNoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VehicleNoFieldActionPerformed

    private void BicycleBrandFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BicycleBrandFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BicycleBrandFieldActionPerformed

    private void BicycleModelFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BicycleModelFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BicycleModelFieldActionPerformed

    private void BicycleTypeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BicycleTypeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BicycleTypeFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BicyclePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BicyclePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BicyclePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BicyclePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BicyclePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JTextField BicycleBrandField;
    private javax.swing.JTextField BicycleColorField;
    private javax.swing.JTextField BicycleCostHr;
    private javax.swing.JTextField BicycleModelField;
    private javax.swing.JPanel BicyclePanel;
    private javax.swing.JTextField BicycleTypeField;
    private javax.swing.JButton BookButton;
    private javax.swing.JPanel NavPanel;
    private javax.swing.JLabel VehiclABEL;
    private javax.swing.JTextField VehicleNoField;
    private javax.swing.JTextField WheelSizeField;
    private javax.swing.JLabel bgCar;
    private javax.swing.JLabel copyrightLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JButton navAboutUs;
    private javax.swing.JButton navFeedback;
    private javax.swing.JButton navHome;
    private javax.swing.JButton navReservation;
    private javax.swing.JButton navSignUp;
    private javax.swing.JButton navUserProfile;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
