/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databaseproject;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author smart view
 */
public class BikePage extends javax.swing.JFrame {

    /**
     * Creates new form bikePage
     */
    String search;
    String vehicleNo;
    String bkBrand;
    String bkModel;
    String bkColor;
    String bkCC;
    String bkFuel;
    String bkCostHr;
    ConnectMSSQL cnObj = new ConnectMSSQL();
    Statement statement;
    
    public BikePage() {
        initComponents();
        setResizable(false);
        /*searchMenu.add(searchPanel);*/
        cnObj.connectDB();
    }
     ArrayList<String> reservationForm = new ArrayList<String>(); 
    public void setReservation(ArrayList<String> Form){
    reservationForm=Form;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        searchPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchList = new javax.swing.JList<>();
        searchMenu = new javax.swing.JPopupMenu();
        jPanel10 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        BikePanel = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        BikeBrandLabel = new javax.swing.JLabel();
        VehicleNoField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        BikeBrandField = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        BikeModelField = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        BikeColorField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        BikeCCField = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        BikeCostHr = new javax.swing.JTextField();
        BookButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        BikeRegField = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        BikeFuelField = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        searchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        bgCar = new javax.swing.JLabel();
        NavPanel = new javax.swing.JPanel();
        navReservation = new javax.swing.JButton();
        navUserProfile = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        copyrightLabel = new javax.swing.JLabel();
        navHome = new javax.swing.JButton();
        navAboutUs = new javax.swing.JButton();
        navSignUp = new javax.swing.JButton();
        navFeedback = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(null);

        jPanel2.setLayout(null);
        jPanel2.add(jTextField1);
        jTextField1.setBounds(10, 150, 180, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(210, 150, 79, 23);

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));
        jPanel4.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bike Booking");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(30, 20, 250, 60);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(0, 0, 300, 90);

        jPanel5.setLayout(null);
        jPanel5.add(jLabel2);
        jLabel2.setBounds(0, 0, 300, 250);

        jPanel2.add(jPanel5);
        jPanel5.setBounds(0, 190, 300, 250);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(50, 20, 300, 440);

        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Brand Name :");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(10, 110, 100, 14);
        jPanel3.add(jTextField2);
        jTextField2.setBounds(120, 100, 150, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Model Name :");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(10, 140, 94, 17);
        jPanel3.add(jTextField3);
        jTextField3.setBounds(120, 140, 150, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("CC :");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(10, 190, 29, 17);
        jPanel3.add(jTextField4);
        jTextField4.setBounds(120, 180, 150, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("color :");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 220, 60, 20);
        jPanel3.add(jTextField5);
        jTextField5.setBounds(120, 220, 150, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Cost/hr :");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(10, 260, 70, 20);
        jPanel3.add(jTextField6);
        jTextField6.setBounds(120, 260, 150, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Model ID :");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(10, 300, 80, 20);
        jPanel3.add(jTextField7);
        jTextField7.setBounds(120, 300, 150, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("BOOK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(200, 390, 75, 25);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(20, 390, 73, 23);

        jPanel6.setBackground(new java.awt.Color(0, 51, 51));
        jPanel6.setLayout(null);
        jPanel3.add(jPanel6);
        jPanel6.setBounds(0, 0, 300, 90);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(380, 20, 300, 440);

        searchPanel.setMaximumSize(new java.awt.Dimension(220, 40));
        searchPanel.setMinimumSize(new java.awt.Dimension(220, 40));
        searchPanel.setName(""); // NOI18N
        searchPanel.setPreferredSize(new java.awt.Dimension(220, 40));
        searchPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchList.setFont(new java.awt.Font("MS PGothic", 0, 16)); // NOI18N
        jScrollPane1.setViewportView(searchList);

        searchPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 358, 220));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Brand Name :");
        jPanel10.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 100, 20));

        jTextField8.setEditable(false);
        jTextField8.setMaximumSize(new java.awt.Dimension(210, 40));
        jTextField8.setMinimumSize(new java.awt.Dimension(210, 40));
        jTextField8.setPreferredSize(new java.awt.Dimension(210, 40));
        jPanel10.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 210, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Model Name :");
        jPanel10.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 100, 30));

        jTextField9.setEditable(false);
        jTextField9.setMaximumSize(new java.awt.Dimension(210, 40));
        jTextField9.setMinimumSize(new java.awt.Dimension(210, 40));
        jTextField9.setPreferredSize(new java.awt.Dimension(210, 40));
        jPanel10.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 210, 40));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Seat :");
        jPanel10.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 50, 30));

        jTextField10.setEditable(false);
        jTextField10.setMaximumSize(new java.awt.Dimension(210, 40));
        jTextField10.setMinimumSize(new java.awt.Dimension(210, 40));
        jTextField10.setPreferredSize(new java.awt.Dimension(210, 40));
        jPanel10.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 210, 40));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("CC :");
        jPanel10.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 50, 20));

        jTextField11.setEditable(false);
        jTextField11.setMaximumSize(new java.awt.Dimension(210, 40));
        jTextField11.setMinimumSize(new java.awt.Dimension(210, 40));
        jTextField11.setPreferredSize(new java.awt.Dimension(210, 40));
        jPanel10.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 210, 40));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Color :");
        jPanel10.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, 20));

        jTextField12.setEditable(false);
        jTextField12.setMaximumSize(new java.awt.Dimension(210, 40));
        jTextField12.setMinimumSize(new java.awt.Dimension(210, 40));
        jPanel10.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 210, 40));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Cost/hr :");
        jPanel10.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 70, 20));

        jTextField13.setEditable(false);
        jTextField13.setMaximumSize(new java.awt.Dimension(210, 40));
        jTextField13.setMinimumSize(new java.awt.Dimension(210, 40));
        jTextField13.setPreferredSize(new java.awt.Dimension(210, 40));
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        jPanel10.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 210, 40));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Model ID :");
        jPanel10.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 80, 20));

        jTextField14.setEditable(false);
        jTextField14.setMaximumSize(new java.awt.Dimension(210, 40));
        jTextField14.setMinimumSize(new java.awt.Dimension(210, 40));
        jTextField14.setPreferredSize(new java.awt.Dimension(210, 40));
        jPanel10.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 210, -1));

        jButton4.setBackground(new java.awt.Color(0, 153, 153));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Book");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 80, 40));

        jButton5.setBackground(new java.awt.Color(153, 0, 153));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 90, 40));

        jPanel11.setBackground(new java.awt.Color(51, 0, 51));
        jPanel11.setForeground(new java.awt.Color(51, 0, 51));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Details");
        jPanel11.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 70));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1270, 680));
        setLocation(new java.awt.Point(0, 0));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1270, 680));
        setMaximumSize(new java.awt.Dimension(1270, 680));
        setMinimumSize(new java.awt.Dimension(1270, 680));
        setResizable(false);
        setSize(new java.awt.Dimension(1270, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BikePanel.setBackground(new java.awt.Color(204, 204, 204));
        BikePanel.setMaximumSize(new java.awt.Dimension(1150, 680));
        BikePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BikeBrandLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BikeBrandLabel.setText("Brand Name :");
        jPanel12.add(BikeBrandLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 100, 20));

        VehicleNoField.setEditable(false);
        VehicleNoField.setBackground(new java.awt.Color(204, 187, 187));
        VehicleNoField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        VehicleNoField.setMaximumSize(new java.awt.Dimension(210, 40));
        VehicleNoField.setMinimumSize(new java.awt.Dimension(210, 40));
        VehicleNoField.setPreferredSize(new java.awt.Dimension(210, 40));
        VehicleNoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VehicleNoFieldActionPerformed(evt);
            }
        });
        jPanel12.add(VehicleNoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 210, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Model Name :");
        jPanel12.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 100, 30));

        BikeBrandField.setEditable(false);
        BikeBrandField.setBackground(new java.awt.Color(204, 187, 187));
        BikeBrandField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BikeBrandField.setMaximumSize(new java.awt.Dimension(210, 40));
        BikeBrandField.setMinimumSize(new java.awt.Dimension(210, 40));
        BikeBrandField.setPreferredSize(new java.awt.Dimension(210, 40));
        jPanel12.add(BikeBrandField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 210, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Fuel :");
        jPanel12.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 50, 20));

        BikeModelField.setEditable(false);
        BikeModelField.setBackground(new java.awt.Color(204, 187, 187));
        BikeModelField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BikeModelField.setMaximumSize(new java.awt.Dimension(210, 40));
        BikeModelField.setMinimumSize(new java.awt.Dimension(210, 40));
        BikeModelField.setPreferredSize(new java.awt.Dimension(210, 40));
        BikeModelField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BikeModelFieldActionPerformed(evt);
            }
        });
        jPanel12.add(BikeModelField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 210, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Color :");
        jPanel12.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, 20));

        BikeColorField.setEditable(false);
        BikeColorField.setBackground(new java.awt.Color(204, 187, 187));
        BikeColorField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BikeColorField.setMaximumSize(new java.awt.Dimension(210, 40));
        BikeColorField.setMinimumSize(new java.awt.Dimension(210, 40));
        BikeColorField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BikeColorFieldActionPerformed(evt);
            }
        });
        jPanel12.add(BikeColorField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 210, 30));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("Cost/hr :");
        jPanel12.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 70, 20));

        BikeCCField.setEditable(false);
        BikeCCField.setBackground(new java.awt.Color(204, 187, 187));
        BikeCCField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BikeCCField.setMaximumSize(new java.awt.Dimension(210, 40));
        BikeCCField.setMinimumSize(new java.awt.Dimension(210, 40));
        BikeCCField.setPreferredSize(new java.awt.Dimension(210, 40));
        BikeCCField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BikeCCFieldActionPerformed(evt);
            }
        });
        jPanel12.add(BikeCCField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 210, 30));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("Vehicle No :");
        jPanel12.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 100, 20));

        BikeCostHr.setEditable(false);
        BikeCostHr.setBackground(new java.awt.Color(204, 187, 187));
        BikeCostHr.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BikeCostHr.setMaximumSize(new java.awt.Dimension(210, 40));
        BikeCostHr.setMinimumSize(new java.awt.Dimension(210, 40));
        BikeCostHr.setPreferredSize(new java.awt.Dimension(210, 40));
        BikeCostHr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BikeCostHrActionPerformed(evt);
            }
        });
        jPanel12.add(BikeCostHr, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 210, 30));

        BookButton.setBackground(new java.awt.Color(0, 153, 153));
        BookButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BookButton.setText("Book");
        BookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookButtonActionPerformed(evt);
            }
        });
        jPanel12.add(BookButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 80, 40));

        BackButton.setBackground(new java.awt.Color(153, 0, 153));
        BackButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        jPanel12.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 90, 40));

        jPanel13.setBackground(new java.awt.Color(51, 0, 51));
        jPanel13.setForeground(new java.awt.Color(51, 0, 51));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Details");
        jPanel13.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jPanel12.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 70));

        BikeRegField.setEditable(false);
        BikeRegField.setBackground(new java.awt.Color(204, 187, 187));
        BikeRegField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BikeRegField.setMaximumSize(new java.awt.Dimension(210, 40));
        BikeRegField.setMinimumSize(new java.awt.Dimension(210, 40));
        BikeRegField.setPreferredSize(new java.awt.Dimension(210, 40));
        BikeRegField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BikeRegFieldActionPerformed(evt);
            }
        });
        jPanel12.add(BikeRegField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 210, 30));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setText("CC :");
        jPanel12.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 50, 20));

        BikeFuelField.setEditable(false);
        BikeFuelField.setBackground(new java.awt.Color(204, 187, 187));
        BikeFuelField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BikeFuelField.setMaximumSize(new java.awt.Dimension(210, 40));
        BikeFuelField.setMinimumSize(new java.awt.Dimension(210, 40));
        BikeFuelField.setPreferredSize(new java.awt.Dimension(210, 40));
        BikeFuelField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BikeFuelFieldActionPerformed(evt);
            }
        });
        jPanel12.add(BikeFuelField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 210, 30));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setText("Registration No :");
        jPanel12.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, 20));

        BikePanel.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, 400, 520));

        jLabel11.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Bike Reservation");
        BikePanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 600, 50));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });
        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchFieldKeyReleased(evt);
            }
        });
        jPanel7.add(searchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 220, 40));

        searchButton.setBackground(new java.awt.Color(255, 204, 204));
        searchButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        searchButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchButtonKeyReleased(evt);
            }
        });
        jPanel7.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 90, 40));

        jPanel8.setLayout(null);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseproject/images/bikeInfo.jpg"))); // NOI18N
        jPanel8.add(jLabel9);
        jLabel9.setBounds(0, 0, 400, 320);

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 400, 320));

        jPanel9.setBackground(new java.awt.Color(51, 0, 51));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Bike");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 70));

        BikePanel.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 400, 520));

        bgCar.setBackground(new java.awt.Color(153, 153, 153));
        bgCar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseproject/images/bg1.jpg"))); // NOI18N
        bgCar.setMaximumSize(new java.awt.Dimension(1150, 680));
        bgCar.setMinimumSize(new java.awt.Dimension(1150, 680));
        BikePanel.add(bgCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 680));

        getContentPane().add(BikePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, -1));

        NavPanel.setBackground(new java.awt.Color(51, 51, 51));
        NavPanel.setMaximumSize(new java.awt.Dimension(120, 680));
        NavPanel.setMinimumSize(new java.awt.Dimension(120, 680));
        NavPanel.setPreferredSize(new java.awt.Dimension(120, 680));
        NavPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navReservation.setBackground(new java.awt.Color(51, 51, 51));
        navReservation.setForeground(new java.awt.Color(255, 255, 255));
        navReservation.setText("RESERVATION");
        navReservation.setToolTipText("");
        navReservation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        navReservation.setMargin(new java.awt.Insets(0, 14, 0, 14));
        navReservation.setMaximumSize(new java.awt.Dimension(77, 30));
        navReservation.setMinimumSize(new java.awt.Dimension(77, 30));
        navReservation.setPreferredSize(new java.awt.Dimension(77, 30));
        navReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navReservationActionPerformed(evt);
            }
        });
        NavPanel.add(navReservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 120, 45));

        navUserProfile.setBackground(new java.awt.Color(51, 51, 51));
        navUserProfile.setForeground(new java.awt.Color(255, 255, 255));
        navUserProfile.setText("USER PROFILE");
        navUserProfile.setToolTipText("");
        navUserProfile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        navUserProfile.setMargin(new java.awt.Insets(0, 14, 0, 14));
        navUserProfile.setMaximumSize(new java.awt.Dimension(77, 30));
        navUserProfile.setMinimumSize(new java.awt.Dimension(77, 30));
        navUserProfile.setPreferredSize(new java.awt.Dimension(77, 30));
        navUserProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navUserProfileActionPerformed(evt);
            }
        });
        NavPanel.add(navUserProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 120, 45));

        titleLabel.setBackground(new java.awt.Color(153, 153, 153));
        titleLabel.setFont(new java.awt.Font("Wide Latin", 3, 14)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(204, 0, 0));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titleLabel.setText("RentAll");
        NavPanel.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 10, 110, 64));

        copyrightLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 2, 16)); // NOI18N
        copyrightLabel.setForeground(new java.awt.Color(255, 255, 255));
        copyrightLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        copyrightLabel.setText("<html><body>Copyright<br>&copy;RentAll</body></html>");
        NavPanel.add(copyrightLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 100, 38));

        navHome.setBackground(new java.awt.Color(51, 51, 51));
        navHome.setForeground(new java.awt.Color(255, 255, 255));
        navHome.setText("HOME");
        navHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        navHome.setMargin(new java.awt.Insets(0, 14, 0, 14));
        navHome.setMaximumSize(new java.awt.Dimension(77, 30));
        navHome.setMinimumSize(new java.awt.Dimension(77, 30));
        navHome.setName(""); // NOI18N
        navHome.setPreferredSize(new java.awt.Dimension(77, 30));
        navHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navHomeActionPerformed(evt);
            }
        });
        NavPanel.add(navHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 120, 45));

        navAboutUs.setBackground(new java.awt.Color(51, 51, 51));
        navAboutUs.setForeground(new java.awt.Color(255, 255, 255));
        navAboutUs.setText("ABOUT US");
        navAboutUs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        navAboutUs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        navAboutUs.setMargin(new java.awt.Insets(0, 14, 0, 14));
        navAboutUs.setMaximumSize(new java.awt.Dimension(77, 30));
        navAboutUs.setMinimumSize(new java.awt.Dimension(77, 30));
        navAboutUs.setName(""); // NOI18N
        navAboutUs.setPreferredSize(new java.awt.Dimension(77, 30));
        navAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navAboutUsActionPerformed(evt);
            }
        });
        NavPanel.add(navAboutUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 120, 45));

        navSignUp.setBackground(new java.awt.Color(51, 51, 51));
        navSignUp.setForeground(new java.awt.Color(255, 255, 255));
        navSignUp.setText("SIGN UP");
        navSignUp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        navSignUp.setMargin(new java.awt.Insets(0, 14, 0, 14));
        navSignUp.setMaximumSize(new java.awt.Dimension(77, 30));
        navSignUp.setMinimumSize(new java.awt.Dimension(77, 30));
        navSignUp.setName(""); // NOI18N
        navSignUp.setPreferredSize(new java.awt.Dimension(77, 30));
        navSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navSignUpActionPerformed(evt);
            }
        });
        NavPanel.add(navSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 120, 45));

        navFeedback.setBackground(new java.awt.Color(51, 51, 51));
        navFeedback.setForeground(new java.awt.Color(255, 255, 255));
        navFeedback.setText("FEEDBACK");
        navFeedback.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        navFeedback.setMargin(new java.awt.Insets(0, 14, 0, 14));
        navFeedback.setMaximumSize(new java.awt.Dimension(120, 45));
        navFeedback.setMinimumSize(new java.awt.Dimension(120, 45));
        navFeedback.setName(""); // NOI18N
        navFeedback.setPreferredSize(new java.awt.Dimension(120, 45));
        navFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navFeedbackActionPerformed(evt);
            }
        });
        NavPanel.add(navFeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 120, 45));

        getContentPane().add(NavPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new VehiclePage().setVisible(true);  
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new ReservationPage().setVisible(true);  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void searchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyReleased
        // TODO add your handling code here:
        /*String search=searchField.getText().trim();
        if(!search.equals("")){
            System.out.println("search");
        }
        searchMenu.setVisible(true);
        searchMenu.show(searchField,0,searchField.getHeight());*/
    }//GEN-LAST:event_searchFieldKeyReleased

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        search=searchField.getText();
        if(search.equals(""))
        {
            JOptionPane.showMessageDialog(this, "This bike is not available.");    
        }
        else
        { 
        try {
            statement = cnObj.connection.createStatement(); 
            ResultSet resultSet= statement.executeQuery("SELECT BIKE.VehicleId, BrandName, ModelName, RegistrationNo, Color, BikeCC, FuelType, CostPerHour FROM BIKE JOIN VEHICLE ON BIKE.VehicleId = VEHICLE.VehicleId AND ModelName ='"+search+"'");
            
             if (resultSet.next()) {
                VehicleNoField.setText(resultSet.getString("VehicleId"));
                BikeBrandField.setText(resultSet.getString("BrandName"));
                BikeModelField.setText(resultSet.getString("ModelName"));
                BikeRegField.setText(resultSet.getString("RegistrationNo"));
                BikeColorField.setText(resultSet.getString("Color"));
                BikeCCField.setText(resultSet.getString("BikeCC"));
                BikeFuelField.setText(resultSet.getString("FuelType"));
                BikeCostHr.setText(resultSet.getString("CostPerHour"));
            }

        } catch (SQLException ex) {
            Logger.getLogger(CarPage.class.getName()).log(Level.SEVERE, null, ex);
        }   
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void searchButtonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchButtonKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonKeyReleased

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new ReservationPage().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new VehiclePage().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void navReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navReservationActionPerformed
        // TODO add your handling code here:
        new ReservationPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_navReservationActionPerformed

    private void navUserProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navUserProfileActionPerformed
        // TODO add your handling code here:
        new UserProfilePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_navUserProfileActionPerformed

    private void navHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navHomeActionPerformed
        // TODO add your handling code here:
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_navHomeActionPerformed

    private void navAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navAboutUsActionPerformed
        // TODO add your handling code here:
        new AboutUsPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_navAboutUsActionPerformed

    private void navSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navSignUpActionPerformed
        // TODO add your handling code here:
        new SignUpPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_navSignUpActionPerformed

    private void navFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navFeedbackActionPerformed
        // TODO add your handling code here:
        new FeedbackPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_navFeedbackActionPerformed

    private void BikeCCFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BikeCCFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BikeCCFieldActionPerformed

    private void BookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookButtonActionPerformed
        // TODO add your handling code here:
        //new ConfirmationPage().setVisible(true);
        this.dispose();
        ConfirmationPage cfp= new ConfirmationPage();
        // ArrayList<String> reservationForm = new ArrayList<String>();
        cfp.setVisible(true);       
        reservationForm.add(VehicleNoField.getText());
        reservationForm.add(BikeBrandField.getText());
        reservationForm.add(BikeModelField.getText());
        reservationForm.add(BikeCostHr.getText());         
        cfp.setReservation(reservationForm);  
    }//GEN-LAST:event_BookButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        new VehiclePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void BikeRegFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BikeRegFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BikeRegFieldActionPerformed

    private void BikeFuelFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BikeFuelFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BikeFuelFieldActionPerformed

    private void VehicleNoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VehicleNoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VehicleNoFieldActionPerformed

    private void BikeModelFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BikeModelFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BikeModelFieldActionPerformed

    private void BikeColorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BikeColorFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BikeColorFieldActionPerformed

    private void BikeCostHrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BikeCostHrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BikeCostHrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BikePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BikePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BikePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BikePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BikePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JTextField BikeBrandField;
    private javax.swing.JLabel BikeBrandLabel;
    private javax.swing.JTextField BikeCCField;
    private javax.swing.JTextField BikeColorField;
    private javax.swing.JTextField BikeCostHr;
    private javax.swing.JTextField BikeFuelField;
    private javax.swing.JTextField BikeModelField;
    private javax.swing.JPanel BikePanel;
    private javax.swing.JTextField BikeRegField;
    private javax.swing.JButton BookButton;
    private javax.swing.JPanel NavPanel;
    private javax.swing.JTextField VehicleNoField;
    private javax.swing.JLabel bgCar;
    private javax.swing.JLabel copyrightLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton navAboutUs;
    private javax.swing.JButton navFeedback;
    private javax.swing.JButton navHome;
    private javax.swing.JButton navReservation;
    private javax.swing.JButton navSignUp;
    private javax.swing.JButton navUserProfile;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JList<String> searchList;
    private javax.swing.JPopupMenu searchMenu;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
