/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databaseproject;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author smart view
 */
public class LoginPage extends javax.swing.JFrame {

    String logphn;
    String logpass;
    ConnectMSSQL cnObj = new ConnectMSSQL();
    Statement statement;
    
    public LoginPage() {
        initComponents();
        setResizable(false);
        cnObj.connectDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        jMenu1 = new javax.swing.JMenu();
        LoginPanel = new javax.swing.JPanel();
        createLabel = new javax.swing.JLabel();
        headingLabel = new javax.swing.JLabel();
        phoneField = new javax.swing.JTextField();
        phoneLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        passwordLabel = new javax.swing.JLabel();
        createButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        bgLogin = new javax.swing.JLabel();
        ZNavPanel = new javax.swing.JPanel();
        navFeedback = new javax.swing.JButton();
        navReservation = new javax.swing.JButton();
        navUserProfile = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        copyrightLabel = new javax.swing.JLabel();
        navHome = new javax.swing.JButton();
        navAboutUs = new javax.swing.JButton();
        navSignUp = new javax.swing.JButton();

        popupMenu1.setLabel("popupMenu1");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1270, 680));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Tw Cen MT", 0, 10)); // NOI18N
        setLocation(new java.awt.Point(0, 0));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1270, 680));
        setMaximumSize(new java.awt.Dimension(1270, 680));
        setMinimumSize(new java.awt.Dimension(1270, 680));
        setName("LoginFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1270, 680));
        setResizable(false);
        setSize(new java.awt.Dimension(1270, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginPanel.setBackground(new java.awt.Color(51, 51, 51));
        LoginPanel.setInheritsPopupMenu(true);
        LoginPanel.setMaximumSize(new java.awt.Dimension(1150, 680));
        LoginPanel.setMinimumSize(new java.awt.Dimension(1150, 680));
        LoginPanel.setName("LoginPanel"); // NOI18N
        LoginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createLabel.setFont(new java.awt.Font("Tw Cen MT", 2, 16)); // NOI18N
        createLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        createLabel.setText("Already have an account?");
        LoginPanel.add(createLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 370, 160, 60));

        headingLabel.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        headingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headingLabel.setText("Login");
        LoginPanel.add(headingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 420, 70));

        phoneField.setBackground(new java.awt.Color(255, 250, 244));
        phoneField.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        phoneField.setMaximumSize(new java.awt.Dimension(220, 50));
        phoneField.setMinimumSize(new java.awt.Dimension(220, 50));
        phoneField.setPreferredSize(new java.awt.Dimension(220, 50));
        LoginPanel.add(phoneField, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 150, -1, -1));
        phoneField.getAccessibleContext().setAccessibleDescription("");

        phoneLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        phoneLabel.setText("Phone:");
        LoginPanel.add(phoneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, 80, 30));

        passwordField.setBackground(new java.awt.Color(255, 250, 244));
        passwordField.setMaximumSize(new java.awt.Dimension(220, 50));
        passwordField.setMinimumSize(new java.awt.Dimension(220, 50));
        passwordField.setPreferredSize(new java.awt.Dimension(220, 50));
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        LoginPanel.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 220, -1, -1));

        passwordLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        passwordLabel.setText("Password:");
        LoginPanel.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 230, 90, 30));

        createButton.setBackground(new java.awt.Color(255, 255, 255));
        createButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        createButton.setForeground(new java.awt.Color(204, 0, 51));
        createButton.setText("Create Account");
        createButton.setContentAreaFilled(false);
        createButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        LoginPanel.add(createButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 380, 140, 40));

        loginButton.setBackground(new java.awt.Color(204, 153, 0));
        loginButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loginButton.setText("Login");
        loginButton.setMaximumSize(new java.awt.Dimension(110, 50));
        loginButton.setMinimumSize(new java.awt.Dimension(110, 50));
        loginButton.setPreferredSize(new java.awt.Dimension(110, 50));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        LoginPanel.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 310, 110, 50));

        bgLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseproject/images/LoginBg.jpg"))); // NOI18N
        bgLogin.setLabelFor(bgLogin);
        bgLogin.setToolTipText("");
        bgLogin.setMaximumSize(new java.awt.Dimension(1150, 680));
        bgLogin.setMinimumSize(new java.awt.Dimension(1150, 680));
        bgLogin.setName("bgLogin"); // NOI18N
        bgLogin.setPreferredSize(new java.awt.Dimension(1150, 680));
        LoginPanel.add(bgLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 680));

        getContentPane().add(LoginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 1150, 680));

        ZNavPanel.setBackground(new java.awt.Color(51, 51, 51));
        ZNavPanel.setMaximumSize(new java.awt.Dimension(120, 680));
        ZNavPanel.setMinimumSize(new java.awt.Dimension(120, 680));
        ZNavPanel.setPreferredSize(new java.awt.Dimension(120, 680));
        ZNavPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navFeedback.setBackground(new java.awt.Color(51, 51, 51));
        navFeedback.setForeground(new java.awt.Color(255, 255, 255));
        navFeedback.setText("FEEDBACK");
        navFeedback.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        navFeedback.setMargin(new java.awt.Insets(0, 14, 0, 14));
        navFeedback.setMaximumSize(new java.awt.Dimension(120, 45));
        navFeedback.setMinimumSize(new java.awt.Dimension(120, 45));
        navFeedback.setName(""); // NOI18N
        navFeedback.setPreferredSize(new java.awt.Dimension(120, 45));
        navFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navFeedbackActionPerformed(evt);
            }
        });
        ZNavPanel.add(navFeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 120, 45));

        navReservation.setBackground(new java.awt.Color(51, 51, 51));
        navReservation.setForeground(new java.awt.Color(255, 255, 255));
        navReservation.setText("RESERVATION");
        navReservation.setToolTipText("");
        navReservation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        navReservation.setMargin(new java.awt.Insets(0, 14, 0, 14));
        navReservation.setMaximumSize(new java.awt.Dimension(120, 45));
        navReservation.setMinimumSize(new java.awt.Dimension(120, 45));
        navReservation.setPreferredSize(new java.awt.Dimension(120, 45));
        navReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navReservationActionPerformed(evt);
            }
        });
        ZNavPanel.add(navReservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 120, 45));

        navUserProfile.setBackground(new java.awt.Color(51, 51, 51));
        navUserProfile.setForeground(new java.awt.Color(255, 255, 255));
        navUserProfile.setText("USER PROFILE");
        navUserProfile.setToolTipText("");
        navUserProfile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        navUserProfile.setMargin(new java.awt.Insets(0, 14, 0, 14));
        navUserProfile.setMaximumSize(new java.awt.Dimension(120, 45));
        navUserProfile.setMinimumSize(new java.awt.Dimension(120, 45));
        navUserProfile.setPreferredSize(new java.awt.Dimension(120, 45));
        navUserProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navUserProfileActionPerformed(evt);
            }
        });
        ZNavPanel.add(navUserProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 120, 45));

        titleLabel.setBackground(new java.awt.Color(153, 153, 153));
        titleLabel.setFont(new java.awt.Font("Wide Latin", 3, 14)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(204, 0, 0));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titleLabel.setText("RentAll");
        ZNavPanel.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 10, 110, 64));

        copyrightLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 2, 16)); // NOI18N
        copyrightLabel.setForeground(new java.awt.Color(255, 255, 255));
        copyrightLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        copyrightLabel.setText("<html><body>Copyright<br>&copy;RentAll</body></html>");
        ZNavPanel.add(copyrightLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 100, 38));

        navHome.setBackground(new java.awt.Color(51, 51, 51));
        navHome.setForeground(new java.awt.Color(255, 255, 255));
        navHome.setText("HOME");
        navHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        navHome.setMargin(new java.awt.Insets(0, 14, 0, 14));
        navHome.setMaximumSize(new java.awt.Dimension(120, 45));
        navHome.setMinimumSize(new java.awt.Dimension(120, 45));
        navHome.setName(""); // NOI18N
        navHome.setPreferredSize(new java.awt.Dimension(120, 45));
        navHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navHomeActionPerformed(evt);
            }
        });
        ZNavPanel.add(navHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 120, 45));

        navAboutUs.setBackground(new java.awt.Color(51, 51, 51));
        navAboutUs.setForeground(new java.awt.Color(255, 255, 255));
        navAboutUs.setText("ABOUT US");
        navAboutUs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        navAboutUs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        navAboutUs.setMargin(new java.awt.Insets(0, 14, 0, 14));
        navAboutUs.setMaximumSize(new java.awt.Dimension(120, 45));
        navAboutUs.setMinimumSize(new java.awt.Dimension(120, 45));
        navAboutUs.setName(""); // NOI18N
        navAboutUs.setPreferredSize(new java.awt.Dimension(77, 30));
        navAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navAboutUsActionPerformed(evt);
            }
        });
        ZNavPanel.add(navAboutUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 120, 45));

        navSignUp.setBackground(new java.awt.Color(51, 51, 51));
        navSignUp.setForeground(new java.awt.Color(255, 255, 255));
        navSignUp.setText("SIGN UP");
        navSignUp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        navSignUp.setMargin(new java.awt.Insets(0, 14, 0, 14));
        navSignUp.setMaximumSize(new java.awt.Dimension(120, 45));
        navSignUp.setMinimumSize(new java.awt.Dimension(120, 45));
        navSignUp.setName(""); // NOI18N
        navSignUp.setPreferredSize(new java.awt.Dimension(120, 45));
        navSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navSignUpActionPerformed(evt);
            }
        });
        ZNavPanel.add(navSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 120, 45));

        getContentPane().add(ZNavPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 680));

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        // TODO add your handling code here:
        new SignUpPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_createButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        //System.out.print(logObj.name);
        ReservationPage logObj = new ReservationPage();
        logphn = phoneField.getText();
        logpass = new String(passwordField.getPassword());
        //System.out.println("Customer pass:" + logpass);
        
        if(logphn.equals("") || logpass.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please insert all the fields.");    
        }
        else
        { 
        try {
            statement = cnObj.connection.createStatement(); 
            ResultSet resultSet= statement.executeQuery("SELECT * FROM CUSTOMER where Phone = "+logphn);
            //System.out.println(resultSet.getString("Password"));
            
             while (resultSet.next()) {
                System.out.println("Customer pass:" + resultSet.getString("Password"));
                System.out.println("Customer phn:" + resultSet.getString("Phone"));
                if(resultSet.getString("Password").equals(logpass))
                {   
                    
                    this.dispose();
                    ArrayList<String> userForm = new ArrayList<String>(); 
                    userForm.add(resultSet.getString("CustomerName"));
                    userForm.add(resultSet.getString("Phone"));
                    userForm.add(resultSet.getString("DrivingLicense"));
                    userForm.add(resultSet.getString("Email"));
                    userForm.add(resultSet.getString("Address"));
                    UserProfilePage up=new UserProfilePage();
                    up.setuser(userForm);
                    up.setVisible(true);

                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Incorrect phone or password.");     
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        }   
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void navFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navFeedbackActionPerformed
        // TODO add your handling code here:
        new FeedbackPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_navFeedbackActionPerformed

    private void navReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navReservationActionPerformed
        // TODO add your handling code here:
        new ReservationPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_navReservationActionPerformed

    private void navHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navHomeActionPerformed
        // TODO add your handling code here:
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_navHomeActionPerformed

    private void navUserProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navUserProfileActionPerformed
        // TODO add your handling code here:
        new UserProfilePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_navUserProfileActionPerformed

    private void navAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navAboutUsActionPerformed
        // TODO add your handling code here:
        new AboutUsPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_navAboutUsActionPerformed

    private void navSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navSignUpActionPerformed
        // TODO add your handling code here:
        new SignUpPage().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_navSignUpActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JPanel ZNavPanel;
    private javax.swing.JLabel bgLogin;
    private javax.swing.JLabel copyrightLabel;
    private javax.swing.JButton createButton;
    private javax.swing.JLabel createLabel;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton navAboutUs;
    private javax.swing.JButton navFeedback;
    private javax.swing.JButton navHome;
    private javax.swing.JButton navReservation;
    private javax.swing.JButton navSignUp;
    private javax.swing.JButton navUserProfile;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField phoneField;
    private javax.swing.JLabel phoneLabel;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
