/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databaseproject;

import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author smart view
 */
public class ReservationPage extends javax.swing.JFrame {

    /**
     * Creates new form reservationPage
     */
    public ReservationPage() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ReservationPanel = new javax.swing.JPanel();
        ReserveTimeField = new javax.swing.JComboBox<>();
        backButton = new javax.swing.JButton();
        pickupPointLabel = new javax.swing.JLabel();
        picupPointField = new javax.swing.JTextField();
        reserveDateLabel = new javax.swing.JLabel();
        reserveHoursLabel = new javax.swing.JLabel();
        CountField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();
        ReserveDateField = new com.toedter.calendar.JDateChooser();
        ReserveHoursField = new javax.swing.JComboBox<>();
        bgReservation = new javax.swing.JLabel();
        Panel1 = new javax.swing.JPanel();
        navReservation = new javax.swing.JButton();
        navUserProfile = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        copyrightLabel = new javax.swing.JLabel();
        navHome = new javax.swing.JButton();
        navAboutUs = new javax.swing.JButton();
        navSignUp = new javax.swing.JButton();
        navFeedback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1270, 680));
        setLocation(new java.awt.Point(0, 0));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1270, 680));
        setMaximumSize(new java.awt.Dimension(1270, 680));
        setMinimumSize(new java.awt.Dimension(1270, 680));
        setResizable(false);
        setSize(new java.awt.Dimension(1270, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ReservationPanel.setBackground(new java.awt.Color(66, 36, 138));
        ReservationPanel.setMaximumSize(new java.awt.Dimension(1050, 680));
        ReservationPanel.setMinimumSize(new java.awt.Dimension(1050, 680));
        ReservationPanel.setPreferredSize(new java.awt.Dimension(1050, 680));
        ReservationPanel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ReservationPanelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        ReservationPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ReserveTimeField.setBackground(new java.awt.Color(204, 204, 255));
        ReserveTimeField.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        ReserveTimeField.setMaximumRowCount(5);
        ReserveTimeField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Time:", "12:00 PM", "01:00 PM", "02:00 PM", "03:00 PM", "04:00 PM", "05:00 PM", "06:00 PM", "07:00 PM", "08:00 PM", "09:00 PM", "10:00 PM", "11:00 PM", "12:00 AM", "01:00 AM", "02:00 AM", "03:00 AM", "04:00 AM", "05:00 AM", "06:00 AM", "07:00 AM", "08:00 AM", "09:00 AM", "10:00 AM", "11:00 AM" }));
        ReserveTimeField.setMaximumSize(new java.awt.Dimension(290, 50));
        ReserveTimeField.setMinimumSize(new java.awt.Dimension(290, 50));
        ReserveTimeField.setPreferredSize(new java.awt.Dimension(290, 50));
        ReserveTimeField.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ReserveTimeFieldAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        ReserveTimeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReserveTimeFieldActionPerformed(evt);
            }
        });
        ReservationPanel.add(ReserveTimeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, -1, -1));

        backButton.setBackground(new java.awt.Color(51, 0, 51));
        backButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.setMaximumSize(new java.awt.Dimension(110, 50));
        backButton.setMinimumSize(new java.awt.Dimension(110, 50));
        backButton.setPreferredSize(new java.awt.Dimension(110, 50));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        ReservationPanel.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 550, 110, 50));

        pickupPointLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pickupPointLabel.setText("Pickup Point :");
        ReservationPanel.add(pickupPointLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 130, 30));

        picupPointField.setBackground(new java.awt.Color(204, 204, 255));
        picupPointField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        picupPointField.setMaximumSize(new java.awt.Dimension(290, 50));
        picupPointField.setMinimumSize(new java.awt.Dimension(290, 50));
        picupPointField.setPreferredSize(new java.awt.Dimension(290, 50));
        picupPointField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                picupPointFieldActionPerformed(evt);
            }
        });
        ReservationPanel.add(picupPointField, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 290, -1));

        reserveDateLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reserveDateLabel.setText("Reservation Date:");
        ReservationPanel.add(reserveDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 140, 40));

        reserveHoursLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reserveHoursLabel.setText("Reservation Hours :");
        ReservationPanel.add(reserveHoursLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 150, 20));

        CountField.setBackground(new java.awt.Color(204, 204, 255));
        CountField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        CountField.setMaximumSize(new java.awt.Dimension(290, 50));
        CountField.setMinimumSize(new java.awt.Dimension(290, 50));
        CountField.setPreferredSize(new java.awt.Dimension(290, 50));
        CountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CountFieldActionPerformed(evt);
            }
        });
        ReservationPanel.add(CountField, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 430, -1, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Starting Time :");
        ReservationPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 120, 30));

        jLabel1.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reservation Information");
        ReservationPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 910, 70));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Vehicle Count:");
        ReservationPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, 110, 30));

        nextButton.setBackground(new java.awt.Color(0, 51, 0));
        nextButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nextButton.setForeground(new java.awt.Color(255, 255, 255));
        nextButton.setText("Next");
        nextButton.setMaximumSize(new java.awt.Dimension(110, 50));
        nextButton.setMinimumSize(new java.awt.Dimension(110, 50));
        nextButton.setPreferredSize(new java.awt.Dimension(110, 50));
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        ReservationPanel.add(nextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 550, -1, -1));

        ReserveDateField.setBackground(new java.awt.Color(204, 204, 255));
        ReserveDateField.setDateFormatString("dd-MM-yyyy");
        ReserveDateField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ReserveDateField.setMaximumSize(new java.awt.Dimension(290, 50));
        ReserveDateField.setMinSelectableDate(new java.util.Date(-62135787500000L));
        ReserveDateField.setMinimumSize(new java.awt.Dimension(290, 50));
        ReserveDateField.setPreferredSize(new java.awt.Dimension(290, 50));
        ReservationPanel.add(ReserveDateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, -1, -1));

        ReserveHoursField.setBackground(new java.awt.Color(204, 204, 255));
        ReserveHoursField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ReserveHoursField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));
        ReserveHoursField.setMaximumSize(new java.awt.Dimension(290, 50));
        ReserveHoursField.setMinimumSize(new java.awt.Dimension(290, 50));
        ReserveHoursField.setPreferredSize(new java.awt.Dimension(290, 50));
        ReserveHoursField.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ReserveHoursFieldAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        ReserveHoursField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReserveHoursFieldActionPerformed(evt);
            }
        });
        ReservationPanel.add(ReserveHoursField, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, -1, -1));

        bgReservation.setBackground(new java.awt.Color(153, 153, 153));
        bgReservation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseproject/images/reserve.jpg"))); // NOI18N
        bgReservation.setMaximumSize(new java.awt.Dimension(1150, 680));
        bgReservation.setMinimumSize(new java.awt.Dimension(1150, 680));
        bgReservation.setPreferredSize(new java.awt.Dimension(1150, 680));
        bgReservation.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                bgReservationAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        ReservationPanel.add(bgReservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 680));

        getContentPane().add(ReservationPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 1150, -1));

        Panel1.setBackground(new java.awt.Color(51, 51, 51));
        Panel1.setMaximumSize(new java.awt.Dimension(120, 680));
        Panel1.setMinimumSize(new java.awt.Dimension(120, 680));
        Panel1.setPreferredSize(new java.awt.Dimension(120, 680));
        Panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navReservation.setBackground(new java.awt.Color(51, 51, 51));
        navReservation.setForeground(new java.awt.Color(255, 255, 255));
        navReservation.setText("RESERVATION");
        navReservation.setToolTipText("");
        navReservation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        navReservation.setMargin(new java.awt.Insets(0, 14, 0, 14));
        navReservation.setMaximumSize(new java.awt.Dimension(77, 30));
        navReservation.setMinimumSize(new java.awt.Dimension(77, 30));
        navReservation.setPreferredSize(new java.awt.Dimension(77, 30));
        navReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navReservationActionPerformed(evt);
            }
        });
        Panel1.add(navReservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 120, 45));

        navUserProfile.setBackground(new java.awt.Color(51, 51, 51));
        navUserProfile.setForeground(new java.awt.Color(255, 255, 255));
        navUserProfile.setText("USER PROFILE");
        navUserProfile.setToolTipText("");
        navUserProfile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        navUserProfile.setMargin(new java.awt.Insets(0, 14, 0, 14));
        navUserProfile.setMaximumSize(new java.awt.Dimension(77, 30));
        navUserProfile.setMinimumSize(new java.awt.Dimension(77, 30));
        navUserProfile.setPreferredSize(new java.awt.Dimension(77, 30));
        navUserProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navUserProfileActionPerformed(evt);
            }
        });
        Panel1.add(navUserProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 120, 45));

        titleLabel.setBackground(new java.awt.Color(153, 153, 153));
        titleLabel.setFont(new java.awt.Font("Wide Latin", 3, 14)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(204, 0, 0));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titleLabel.setText("RentAll");
        Panel1.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 10, 110, 64));

        copyrightLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 2, 16)); // NOI18N
        copyrightLabel.setForeground(new java.awt.Color(255, 255, 255));
        copyrightLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        copyrightLabel.setText("<html><body>Copyright<br>&copy;RentAll</body></html>");
        Panel1.add(copyrightLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 100, 38));

        navHome.setBackground(new java.awt.Color(51, 51, 51));
        navHome.setForeground(new java.awt.Color(255, 255, 255));
        navHome.setText("HOME");
        navHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        navHome.setMargin(new java.awt.Insets(0, 14, 0, 14));
        navHome.setMaximumSize(new java.awt.Dimension(77, 30));
        navHome.setMinimumSize(new java.awt.Dimension(77, 30));
        navHome.setName(""); // NOI18N
        navHome.setPreferredSize(new java.awt.Dimension(77, 30));
        navHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navHomeActionPerformed(evt);
            }
        });
        Panel1.add(navHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 120, 45));

        navAboutUs.setBackground(new java.awt.Color(51, 51, 51));
        navAboutUs.setForeground(new java.awt.Color(255, 255, 255));
        navAboutUs.setText("ABOUT US");
        navAboutUs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        navAboutUs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        navAboutUs.setMargin(new java.awt.Insets(0, 14, 0, 14));
        navAboutUs.setMaximumSize(new java.awt.Dimension(77, 30));
        navAboutUs.setMinimumSize(new java.awt.Dimension(77, 30));
        navAboutUs.setName(""); // NOI18N
        navAboutUs.setPreferredSize(new java.awt.Dimension(77, 30));
        navAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navAboutUsActionPerformed(evt);
            }
        });
        Panel1.add(navAboutUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 120, 45));

        navSignUp.setBackground(new java.awt.Color(51, 51, 51));
        navSignUp.setForeground(new java.awt.Color(255, 255, 255));
        navSignUp.setText("SIGN UP");
        navSignUp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        navSignUp.setMargin(new java.awt.Insets(0, 14, 0, 14));
        navSignUp.setMaximumSize(new java.awt.Dimension(77, 30));
        navSignUp.setMinimumSize(new java.awt.Dimension(77, 30));
        navSignUp.setName(""); // NOI18N
        navSignUp.setPreferredSize(new java.awt.Dimension(77, 30));
        navSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navSignUpActionPerformed(evt);
            }
        });
        Panel1.add(navSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 120, 45));

        navFeedback.setBackground(new java.awt.Color(51, 51, 51));
        navFeedback.setForeground(new java.awt.Color(255, 255, 255));
        navFeedback.setText("FEEDBACK");
        navFeedback.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        navFeedback.setMargin(new java.awt.Insets(0, 14, 0, 14));
        navFeedback.setMaximumSize(new java.awt.Dimension(120, 45));
        navFeedback.setMinimumSize(new java.awt.Dimension(120, 45));
        navFeedback.setName(""); // NOI18N
        navFeedback.setPreferredSize(new java.awt.Dimension(120, 45));
        navFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navFeedbackActionPerformed(evt);
            }
        });
        Panel1.add(navFeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 120, 45));

        getContentPane().add(Panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void navReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navReservationActionPerformed
        // TODO add your handling code here:
        new ReservationPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_navReservationActionPerformed

    private void navUserProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navUserProfileActionPerformed
        // TODO add your handling code here:
        new UserProfilePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_navUserProfileActionPerformed

    private void navHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navHomeActionPerformed
        // TODO add your handling code here:
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_navHomeActionPerformed

    private void navAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navAboutUsActionPerformed
        // TODO add your handling code here:
        new AboutUsPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_navAboutUsActionPerformed

    private void navSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navSignUpActionPerformed
        // TODO add your handling code here:
        new SignUpPage().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_navSignUpActionPerformed

    private void ReserveHoursFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReserveHoursFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReserveHoursFieldActionPerformed

    private void ReserveHoursFieldAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ReserveHoursFieldAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_ReserveHoursFieldAncestorAdded

    private void navFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navFeedbackActionPerformed
        // TODO add your handling code here:
        new FeedbackPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_navFeedbackActionPerformed

    private void ReservationPanelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ReservationPanelAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_ReservationPanelAncestorAdded

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
        //new VehiclePage().setVisible(true
        this.dispose();
        VehiclePage vp= new VehiclePage();
        ArrayList<String> reservationForm = new ArrayList<String>();
        vp.setVisible(true);       
        reservationForm.add(picupPointField.getText());
        Date date = ReserveDateField.getDate();
        String strDate = DateFormat.getDateInstance().format(date);
        reservationForm.add(strDate);
        reservationForm.add(ReserveTimeField.getSelectedItem().toString());
        reservationForm.add(ReserveHoursField.getSelectedItem().toString());
        reservationForm.add(CountField.getText());
        vp.setReservation(reservationForm);  
        
    }//GEN-LAST:event_nextButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void bgReservationAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_bgReservationAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_bgReservationAncestorAdded

    private void ReserveTimeFieldAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ReserveTimeFieldAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_ReserveTimeFieldAncestorAdded

    private void ReserveTimeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReserveTimeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReserveTimeFieldActionPerformed

    private void picupPointFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_picupPointFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_picupPointFieldActionPerformed

    private void CountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CountFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservationPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CountField;
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel ReservationPanel;
    private com.toedter.calendar.JDateChooser ReserveDateField;
    private javax.swing.JComboBox<String> ReserveHoursField;
    private javax.swing.JComboBox<String> ReserveTimeField;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel bgReservation;
    private javax.swing.JLabel copyrightLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton navAboutUs;
    private javax.swing.JButton navFeedback;
    private javax.swing.JButton navHome;
    private javax.swing.JButton navReservation;
    private javax.swing.JButton navSignUp;
    private javax.swing.JButton navUserProfile;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel pickupPointLabel;
    private javax.swing.JTextField picupPointField;
    private javax.swing.JLabel reserveDateLabel;
    private javax.swing.JLabel reserveHoursLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
